name: 'Setup Playwright Browsers'
description: 'Configures and caches Playwright browsers with efficient caching for CI environments'

# Remote usage from another repository:
# - name: Setup Playwright browsers
#   uses: seontechnologies/playwright-utils/setup-playwright-browsers@main
#   with:
#     browser-cache-bust: 'false' # or true to force cache invalidation

inputs:
  browser-cache-bust:
    description: 'Optional value to force browser cache invalidation (set to "true" or a timestamp to bust cache)'
    required: false
    default: 'false'

outputs:
  cache-hit:
    description: 'Whether there was a cache hit for the browser binaries'
    value: ${{ steps.playwright-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    # 1. Detect package manager and extract the exact version of @playwright/test from the appropriate lock file
    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      run: |
        # Auto-detect package manager from lock files
        if [ -f "pnpm-lock.yaml" ]; then
          PACKAGE_MANAGER="pnpm"
        else
          PACKAGE_MANAGER="npm"
        fi
        echo "Using package manager: $PACKAGE_MANAGER"
        
        # Extract Playwright version based on package manager's lock file
        if [ "$PACKAGE_MANAGER" == "pnpm" ]; then
          # For pnpm: Parse the pnpm-lock.yaml file
          if [ -x "$(command -v pnpm)" ]; then
            PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --json | jq -r '.[0].dependencies["@playwright/test"].version')
          else
            # Fallback if pnpm is not installed
            PLAYWRIGHT_VERSION=$(node -e "const fs=require('fs');const yaml=require('yaml');const lock=yaml.parse(fs.readFileSync('pnpm-lock.yaml','utf8'));console.log(Object.values(lock.packages).find(p=>p.name==='@playwright/test').version || '')")
          fi
        else
          # For npm
          PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages['node_modules/@playwright/test'].version || '')")
        fi
        
        # Check if we got a version
        if [ -z "$PLAYWRIGHT_VERSION" ]; then
          echo "Error: Could not determine Playwright version from lock file"
          echo "Please ensure your lock file (package-lock.json or pnpm-lock.yaml) is up to date"
          exit 1
        fi
        
        echo "Detected Playwright version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

        # Add cache busting timestamp if requested
        if [ "${{ inputs.browser-cache-bust }}" == "true" ]; then
          echo "CACHE_BUSTER=$(date +%s)" >> $GITHUB_ENV
          echo "Cache busting enabled for browser installation"
        else
          echo "CACHE_BUSTER=0" >> $GITHUB_ENV
        fi
      # (caches under exactly this version so any upgrade invalidates automatically)

    # 2. Restore browse cache if it exists
    - name: Restore Playwright browser cache
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{ env.CACHE_BUSTER }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-
          ${{ runner.os }}-playwright-
      # (saves/loads browser binaries at ~/.cache/ms-playwright)

    # 3. Only install browser binaries if cache was a MISS
    # (installs browser binaries only, skipped on cache-hit)
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install chromium chrome

    # 4. Always install system dependencies (required even when browsers are cached)
    # Note: browsers are cached but the system dependencies for the browsers cannot be cached
    # System dependencies can't be cached because they're OS-level packages installed across various system directories
    # Our Kubernetes runners start with minimal images that don't include these deps, so we need to install them every time.
    # Sometimes Ubuntu package repos rate-limit us, but this step is necessary for browsers to work.
    # What we would have to do:
    #
      # Current configuration
      # runs-on: kubernetes-default

      # Modified configuration with custom image
      # runs-on: 
      #   kubernetes:
      #     image: seontechnologies/playwright-runner:latest
    #
    # We would need a Dockerfile with all Playwright dependencies pre-installed
      # FROM ubuntu:22.04
      # RUN apt-get update && apt-get install -y --no-install-recommends \
      #     libwoff1 libopus0 libwebp7 libwebpdemux2 libenchant-2-2 libgudev-1.0-0 \
      #     libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libnotify4 \
      #     libxslt1.1 libevent-2.1-7 libgles2 libvpx7 libxcomposite1 \
      #     libatk1.0-0 libatk-bridge2.0-0 libepoxy0 libgtk-3-0 libharfbuzz-icu0 \
      #     libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 gstreamer1.0-plugins-good \
      #     gstreamer1.0-libav gstreamer1.0-plugins-bad gstreamer1.0-gl \
      #     gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps
      # # Add Node.js, npm, and other tools
    #    
    - name: Install Playwright system dependencies
      shell: bash
      run: npx playwright install-deps chromium chrome

    # 5. Verify that browsers are in place for debugging
    # (quick check to confirm the cache or install succeeded)
    - name: Verify Browsers
      shell: bash
      run: |
        npx playwright install --dry-run
        echo "Playwright browsers installed at:"
        ls -la ~/.cache/ms-playwright/